version: '3.8'
services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    working_dir: /var/www/html
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      - "443:8443"
    depends_on:
      - mysql
  web:
    container_name: web
    environment:
        DB_PORT: 3306
        DB_DATABASE: 'database'
        DB_USERNAME: 'username'
        DB_PASSWORD: 'password'
        DB_HOST: 'mysql'
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: ./docker/web.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 81:80
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
